### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by giacomorebonato** [legend80s/eslint-plugin-function-name#1]
I am getting the following output after I add the rule

```
Oops! Something went wrong! :(

ESLint: 8.57.0

TypeError: Cannot read properties of null (reading 'name')
```

Referring to

```
      FunctionDeclaration(node) {
        if (node.type === 'FunctionDeclaration') {
          validate({ context, node, fnName: node.id.name });
        }
      },
```

**Comment by legend80s** [comment]
can you share you code. Maybe a anonymous FunctionDeclaration

**Comment by legend80s** [comment]
You cannot make a anonymous FunctionDeclaration  like `function () {}`. So perhaps your code is syntax invalid.

**Comment by giacomorebonato** [comment]
I'll look into that and let you know. Thanks

**Comment by giacomorebonato** [comment]
That was the reason indeed, I had anonymous functions.

Do you think that those cases should be handled gracefully?

**Comment by legend80s** [comment]
Yes I will. but I am curious about your code because anonymous `FunctionDeclaration` is not valid js. Would you like to show you code snippets so I can add test case for this issue?

```
 FunctionDeclaration(node) {
        if (node.type === 'FunctionDeclaration') {
          validate({ context, node, fnName: node.id.name });
        }
      },
```

**Comment by giacomorebonato** [comment]
I see that the new release is solving the issue.
Before it was breaking when this type of code was found:

```typescript
export default function() {}
```

**Comment by giacomorebonato** [comment]
To clarify, I agree that it's a bad practice, but it's one that I am trying to catch.
Probably this linting rule will come handy too:

https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-anonymous-default-export.md
